linters:
  # Enable all available linters.
  enable-all: true
  # Disable specific linter
  disable:
    - ifshort
    - varcheck
    - deadcode
    - structcheck
    - nosnakecase
    - interfacer
    - exhaustivestruct
    - maligned
    - golint
    - scopelint
    - depguard
    - revive
    - varnamelen
    - exhaustruct
    - gofumpt
    - gci
    - paralleltest
    - funlen
    - dupl
    - wsl
    - testpackage
    - nlreturn
  skip-files:
    - ".*\\_gen\\.go"
    - ".*\\_test\\.go"
    - ".*\\_mock\\.go"
    - ".*\\/migrate\\/main\\.go"
    - ".*\\/migrate\\/migration\\/.*\\.go"
linters-settings:
  wrapcheck:
    ignoreSigs:
      - (github.com/labstack/echo/v4.Context).
      - github.com/cockroachdb/errors.
  cyclop:
    max-complexity: 12
  goconst:
    ignore-tests: true
