openapi: 3.1.0
info:
  version: 1.0.0
  title: Http Server I/F
paths:
  /account/{id}:
    get:
      summary: Returns account by id
      operationId: accountIdGet
      parameters:
        - name: id
          in: path
          description: ID of account to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update account by id
      operationId: accountIdPut
      parameters:
        - name: id
          in: path
          description: ID of account to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /account:
    get:
      summary: Returns account by id
      operationId: accountGet
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Creates a new account
      description: Creates a new account in the store. Duplicates are not allowed
      operationId: addAccount
      requestBody:
        description: Account to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewAccount"
      responses:
        "200":
          description: account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Account:
      allOf:
        - $ref: "#/components/schemas/NewAccount"
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
              description: Unique id of the account
    NewAccount:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the account
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
