// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"awsomeapp/internal/module/account"
	"github.com/uptrace/bun"
	"go.uber.org/mock/gomock"
	"testing"
)

// Injectors from wire.go:

func Wire(db *bun.DB, jwtSigningKey []byte) (*Handlers, error) {
	healthHandler := NewHealthHandler()
	accountUsecase, err := account.Wire(db)
	if err != nil {
		return nil, err
	}
	accountHandler := NewAccountHandler(accountUsecase)
	authHandler := NewAuthHandler(jwtSigningKey)
	handlers := &Handlers{
		HealthHandler:  healthHandler,
		AccountHandler: accountHandler,
		AuthHandler:    authHandler,
	}
	return handlers, nil
}

func WireMock(t *testing.T, jwtSigningKey []byte) (*Handlers, error) {
	healthHandler := NewHealthHandler()
	controller := provideMockController(t)
	mockiAccountUsecase := NewMockiAccountUsecase(controller)
	accountHandler := NewAccountHandler(mockiAccountUsecase)
	authHandler := NewAuthHandler(jwtSigningKey)
	handlers := &Handlers{
		HealthHandler:  healthHandler,
		AccountHandler: accountHandler,
		AuthHandler:    authHandler,
	}
	return handlers, nil
}

// wire.go:

func provideMockController(t gomock.TestReporter) *gomock.Controller {
	return gomock.NewController(t)
}
