// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"awsomeapp/internal/module/account"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func Wire(db *bun.DB) (*Handlers, error) {
	accountUsecase, err := account.Wire(db)
	if err != nil {
		return nil, err
	}
	accountHandler := NewAccountHandler(accountUsecase)
	handlers := &Handlers{
		AccountHandler: accountHandler,
	}
	return handlers, nil
}
