// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"awsomeapp/internal/handler"
	"awsomeapp/internal/handler/account"
	"awsomeapp/internal/repository"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func Wire(db *bun.DB) (*handler.Handlers, error) {
	accountRepository := repository.NewAccountRepository(db)
	accountGetHandler := account.NewAccountGetHandler(accountRepository)
	accountPostHandler := account.NewAccountPostHandler(accountRepository)
	accountPutHandler := account.NewAccountPutHandler(accountRepository)
	handlers := &handler.Handlers{
		AccountGetHandler:  accountGetHandler,
		AccountPostHandler: accountPostHandler,
		AccountPutHandler:  accountPutHandler,
	}
	return handlers, nil
}
