// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"awsomeapp/internal/handler"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func Wire(db *bun.DB) (*handler.Handlers, error) {
	accountHandler := handler.NewAccountHandler(db)
	handlers := &handler.Handlers{
		AccountHandler: accountHandler,
	}
	return handlers, nil
}
