// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

import (
	"awsomeapp/internal/module/account/internal/repository"
	"github.com/uptrace/bun"
	"go.uber.org/mock/gomock"
	"testing"
)

// Injectors from wire.go:

func Wire(db *bun.DB) (*AccountUsecase, error) {
	accountRepository := repository.NewAccountRepository(db)
	accountUsecase := NewAccountUsecase(accountRepository)
	return accountUsecase, nil
}

func WireMock(t *testing.T) (*AccountUsecase, error) {
	controller := provideMockController(t)
	mockiAccountRepository := NewMockiAccountRepository(controller)
	accountUsecase := NewAccountUsecase(mockiAccountRepository)
	return accountUsecase, nil
}

// wire.go:

func provideMockController(t gomock.TestReporter) *gomock.Controller {
	return gomock.NewController(t)
}
