// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/account/internal/domain/iRepo.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/account/internal/domain/iRepo.go -destination=internal/module/account/internal/domain/Repo_mock.go -package=domain -self_package=awsomeapp/internal/module/account/internal/domain
//
// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockiAccountRepository is a mock of iAccountRepository interface.
type MockiAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockiAccountRepositoryMockRecorder
}

// MockiAccountRepositoryMockRecorder is the mock recorder for MockiAccountRepository.
type MockiAccountRepositoryMockRecorder struct {
	mock *MockiAccountRepository
}

// NewMockiAccountRepository creates a new mock instance.
func NewMockiAccountRepository(ctrl *gomock.Controller) *MockiAccountRepository {
	mock := &MockiAccountRepository{ctrl: ctrl}
	mock.recorder = &MockiAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiAccountRepository) EXPECT() *MockiAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockiAccountRepository) Create(udto *AccountUnspecifiedDTO) (*AccountDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", udto)
	ret0, _ := ret[0].(*AccountDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockiAccountRepositoryMockRecorder) Create(udto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockiAccountRepository)(nil).Create), udto)
}

// Delete mocks base method.
func (m *MockiAccountRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockiAccountRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockiAccountRepository)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockiAccountRepository) Get(id string) (*AccountDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*AccountDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockiAccountRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockiAccountRepository)(nil).Get), id)
}

// Update mocks base method.
func (m *MockiAccountRepository) Update(dto *AccountDTO) (*AccountDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", dto)
	ret0, _ := ret[0].(*AccountDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockiAccountRepositoryMockRecorder) Update(dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockiAccountRepository)(nil).Update), dto)
}
